let suggestions = [
    "Canal",
    "Felpszadaa",
    "Youtube",
    "Youtuber",
    "Youtube Channel",
    "Blogger",
    "Hollywood",
    "Vlogger",
    "Veículos",
    "Facebook",
    "Twitter",
    "Instagram",
    "Whatsapp",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to became a Freelancer",
    "How to became Web Designer",
    "How to start Gaming Channel",
    "How to start Youtube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
    "What does JavaScript stands for?"
]